name: Generate Terraform Diagram

on:
  workflow_dispatch:

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai diagrams
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Generate Terraform plan
        run: |
          terraform init
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json

      - name: Generate Diagrams script using OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_diagram_with_openai.py

      - name: Generate diagram
        run: python diagram.py

      - name: Upload diagram
        uses: actions/upload-artifact@v2
        with:
          name: azure-diagram
          path: Azure\ Infrastructure.png
